use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::backend::{proto_message, proto_utils::naive_datetime_to_timestamp};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantMessagePartModel {
    pub id: Uuid,
    pub harness_part_id: Option<String>,
    pub assistant_message_id: Uuid,
    pub session_id: Uuid,
    pub position: i64,
    pub part_type: String,
    pub text: Option<String>,
    pub file_mime: Option<String>,
    pub file_filename: Option<String>,
    pub file_url: Option<String>,
    pub file_source_type: Option<String>,
    pub file_source_path: Option<String>,
    pub file_source_name: Option<String>,
    pub file_source_kind: Option<i64>,
    pub file_source_uri: Option<String>,
    pub file_source_text_value: Option<String>,
    pub file_source_text_start: Option<i64>,
    pub file_source_text_end: Option<i64>,
    pub agent_name: Option<String>,
    pub subtask_prompt: Option<String>,
    pub subtask_description: Option<String>,
    pub subtask_agent: Option<String>,
    pub subtask_model_provider_id: Option<String>,
    pub subtask_model_id: Option<String>,
    pub subtask_command: Option<String>,
    pub tool_call_id: Option<String>,
    pub tool_name: Option<String>,
    pub tool_status: Option<String>,
    pub tool_input_json: Option<String>,
    pub tool_output_text: Option<String>,
    pub tool_error_text: Option<String>,
    pub tool_title: Option<String>,
    pub tool_metadata_json: Option<String>,
    pub tool_compacted_at: Option<i64>,
    pub tool_state_raw: Option<String>,
    pub tool_state_time_start: Option<i64>,
    pub tool_state_time_end: Option<i64>,
    pub tool_state_time_compacted: Option<i64>,
    pub tool_attachments_json: Option<String>,
    pub finish_reason: Option<String>,
    pub cost: Option<f64>,
    pub token_total: Option<i64>,
    pub token_input: Option<i64>,
    pub token_output: Option<i64>,
    pub token_reasoning: Option<i64>,
    pub token_cache_read: Option<i64>,
    pub token_cache_write: Option<i64>,
    pub snapshot_hash: Option<String>,
    pub patch_hash: Option<String>,
    pub patch_files_json: Option<String>,
    pub retry_attempt: Option<i64>,
    pub retry_error_json: Option<String>,
    pub retry_created_at: Option<i64>,
    pub compaction_auto: Option<bool>,
    pub delta_field: Option<String>,
    pub delta_text: Option<String>,
    pub part_time_start: Option<i64>,
    pub part_time_end: Option<i64>,
    pub part_metadata_json: Option<String>,
    pub text_synthetic: Option<bool>,
    pub text_ignored: Option<bool>,
    pub step_snapshot_hash: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

impl From<AssistantMessagePartModel> for proto_message::AssistantMessagePartModel {
    fn from(value: AssistantMessagePartModel) -> Self {
        Self {
            id: value.id.to_string(),
            assistant_message_id: value.assistant_message_id.to_string(),
            session_id: value.session_id.to_string(),
            position: value.position,
            part_type: value.part_type,
            text: value.text,
            file_mime: value.file_mime,
            file_filename: value.file_filename,
            file_url: value.file_url,
            file_source_type: value.file_source_type,
            file_source_path: value.file_source_path,
            file_source_name: value.file_source_name,
            file_source_kind: value.file_source_kind,
            file_source_uri: value.file_source_uri,
            file_source_text_value: value.file_source_text_value,
            file_source_text_start: value.file_source_text_start,
            file_source_text_end: value.file_source_text_end,
            agent_name: value.agent_name,
            subtask_prompt: value.subtask_prompt,
            subtask_description: value.subtask_description,
            subtask_agent: value.subtask_agent,
            subtask_model_provider_id: value.subtask_model_provider_id,
            subtask_model_id: value.subtask_model_id,
            subtask_command: value.subtask_command,
            tool_call_id: value.tool_call_id,
            tool_name: value.tool_name,
            tool_status: value.tool_status,
            tool_input_json: value.tool_input_json,
            tool_output_text: value.tool_output_text,
            tool_error_text: value.tool_error_text,
            tool_title: value.tool_title,
            tool_metadata_json: value.tool_metadata_json,
            tool_compacted_at: value.tool_compacted_at,
            finish_reason: value.finish_reason,
            cost: value.cost,
            token_total: value.token_total,
            token_input: value.token_input,
            token_output: value.token_output,
            token_reasoning: value.token_reasoning,
            token_cache_read: value.token_cache_read,
            token_cache_write: value.token_cache_write,
            snapshot_hash: value.snapshot_hash,
            patch_hash: value.patch_hash,
            patch_files_json: value.patch_files_json,
            retry_attempt: value.retry_attempt,
            retry_error_json: value.retry_error_json,
            retry_created_at: value.retry_created_at,
            compaction_auto: value.compaction_auto,
            created_at: Some(naive_datetime_to_timestamp(value.created_at)),
            updated_at: Some(naive_datetime_to_timestamp(value.updated_at)),
            tool_state_raw: value.tool_state_raw,
            tool_state_time_start: value.tool_state_time_start,
            tool_state_time_end: value.tool_state_time_end,
            tool_state_time_compacted: value.tool_state_time_compacted,
            tool_attachments_json: value.tool_attachments_json,
            delta_field: value.delta_field,
            delta_text: value.delta_text,
            part_time_start: value.part_time_start,
            part_time_end: value.part_time_end,
            part_metadata_json: value.part_metadata_json,
            text_synthetic: value.text_synthetic,
            text_ignored: value.text_ignored,
            step_snapshot_hash: value.step_snapshot_hash,
        }
    }
}
