use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantMessage {
    pub id: Uuid,
    pub session_id: Uuid,
    pub user_message_id: Uuid,
    pub agent: String,
    pub model_provider_id: String,
    pub model_id: String,
    pub cwd: String,
    pub root: String,
    pub cost: f64,
    pub token_total: Option<i64>,
    pub token_input: i64,
    pub token_output: i64,
    pub token_reasoning: i64,
    pub token_cache_read: i64,
    pub token_cache_write: i64,
    pub error_message: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub completed_at: Option<NaiveDateTime>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantMessagePart {
    pub id: Uuid,
    pub assistant_message_id: Uuid,
    pub session_id: Uuid,
    pub position: i64,
    pub part_type: String,
    pub text: Option<String>,
    pub file_mime: Option<String>,
    pub file_filename: Option<String>,
    pub file_url: Option<String>,
    pub file_source_type: Option<String>,
    pub file_source_path: Option<String>,
    pub file_source_name: Option<String>,
    pub file_source_kind: Option<i64>,
    pub file_source_uri: Option<String>,
    pub file_source_text_value: Option<String>,
    pub file_source_text_start: Option<i64>,
    pub file_source_text_end: Option<i64>,
    pub agent_name: Option<String>,
    pub subtask_prompt: Option<String>,
    pub subtask_description: Option<String>,
    pub subtask_agent: Option<String>,
    pub subtask_model_provider_id: Option<String>,
    pub subtask_model_id: Option<String>,
    pub subtask_command: Option<String>,
    pub tool_call_id: Option<String>,
    pub tool_name: Option<String>,
    pub tool_status: Option<String>,
    pub tool_input_json: Option<String>,
    pub tool_output_text: Option<String>,
    pub tool_error_text: Option<String>,
    pub tool_title: Option<String>,
    pub tool_metadata_json: Option<String>,
    pub tool_compacted_at: Option<i64>,
    pub finish_reason: Option<String>,
    pub cost: Option<f64>,
    pub token_total: Option<i64>,
    pub token_input: Option<i64>,
    pub token_output: Option<i64>,
    pub token_reasoning: Option<i64>,
    pub token_cache_read: Option<i64>,
    pub token_cache_write: Option<i64>,
    pub snapshot_hash: Option<String>,
    pub patch_hash: Option<String>,
    pub patch_files_json: Option<String>,
    pub retry_attempt: Option<i64>,
    pub retry_error_json: Option<String>,
    pub retry_created_at: Option<i64>,
    pub compaction_auto: Option<bool>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}
